baseURL = "https://shue.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Shue / 舒舍"                      
theme = "zozo"
hasCJKLanguage = true
summaryLength = 77
paginate = 7
enableEmoji = false
googleAnalytics = ""

rssLimit = 7
enableGitInfo = false
pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]
  name = "舒舍"

[blackfriday]
  smartypants = false

[menu]
  main = [
      {name = "主页", Weight = 1, identifier = "home", url = "/"},
      {name = "标签", Weight = 2, identifier = "tags", url = "/tags/"},
      {name = "归档", Weight = 3, identifier = "archive", url = "/posts/"},
      {name = "关于", Weight = 4, identifier = "about", url = "/about/"}
  ]

[params]
  subTitle = ""                                       # site's subTitle              # 网站二级标题
  footerSlogan = ""                                   # site's footer slogan         # 网站页脚标语
  keywords = ["shue","舒舍"]                                   # site's keywords              # 网站关键字
  description = "Shue's blog."                        # site's description           # 网站描述
#  enableMathJax = false                                                # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts"]
  fancybox = true       # 图片放大功能
[params.footer]
  powered_by = 'Copyright © 2023 Shue'
  Slogan = ""                 
  
[params.twikoo]
  enable = true
  envId = 'https://twikoo.shue.io/'
  twikoojs = 'https://cdn.jsdelivr.net/npm/twikoo@1.6.11/dist/twikoo.min.js'  
  
[social]
  github = "https://github.com/shueio"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  posts = "/:filename"
  hidden = "/:filename"
  pages = "/:filename"
[taxonomies]
  tag = "tags"
