baseURL = "https://shue.io/"
languageCode = "zh-cn"
title = "Shue / 舒舍"
disableKinds = ['taxonomy', 'term']

[author]
  name = "Shue"
  email = "i@shue.io"

[params]
  keywords = ["Shue", "舒舍", "blog"]
  description = "Shue's blog"
  mainSections = ["writing"]

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]

[permalinks]
  writing = "/:filename"
  hidden = "/:filename"
  pages = "/:filename"
  
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true