baseURL = "https://shue.io"
languageCode = "zh-cn"
title = "MianJie"
disableKinds = ['taxonomy', 'term']

[author]
  name = "MianJie"
  email = "shue@tuta.io"

[params]
  keywords = ["免介", "mianjie","shue", "MianJie"]
  description = "博客"
  mainSections = ["writing"]

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]

[permalinks]
  writing = "/:filename"
  hidden = "/:filename"
  pages = "/:filename"
  
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
