baseURL = "https://nidu.city"
languageCode = "zh-cn"
title = "拟都"
disableKinds = ['taxonomy', 'term']

[author]
  name = "MianJie"
  email = "shue@tuta.io"

[params]
  keywords = ["免介", "mianjie","shue", "nidu", "拟都"]
  description = "拟都"
  mainSections = ["writing"]

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]

[permalinks]
  writing = "/:filename"
  hidden = "/:filename"
  pages = "/:filename"
  
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
