baseURL = "https://shue.io/"
languageCode = "zh-cn"
title = "Shue / 舒舍"
disableKinds = ['taxonomy', 'term']

[author]
  name = "Shue"
  email = "i@shue.io"

[params]
  keywords = ["Shue", "舒舍", "blog"]
  description = "Shue's blog"
  mainSections = ["posts"]
  
[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  
[markup.goldmark.renderer]
  unsafe= true
  
[permalinks]
  posts = "/:filename"
  hidden = "/:filename"