#+title: [译]一个我们时代的哲学
#+date: 2023-01-28

*A Philosophy for Our Time[fn:1]
@罗素*

这是我的主题，但我并不认为给我们时代的哲学分配的任务完全不同于其他时代。我相信，哲学有永恒的价值，这不会改变，除非在某方面：某一时代比其他时代更普遍偏离了智慧，以至更需要被动接受哲学。就许多方面而言，我们的时代是一个有很少智慧的时代，但也因此，借助哲学的必须所教之物，此时代可以获益良多。

哲学的价值部分涉及思考，部分涉及感受，然而它的作用在这两方面密切相连。在理论方面，它能帮助将宇宙尽可能地作为一个整体理解。在感受方面，它帮助对人生的尽头持公正的感激态度。我建议首先细想哲学能为我们的思考做些什么，然后是能为我们的感觉做些什么。

** 此处与现在

哲学做的——或应该做的——第一件事是扩展我们大脑的想象力。动物，包括人类，从由此处和现在组成的中心看待世界。我们的感官，如同夜晚的蜡烛，朝不断遥远的物体投射出逐渐减弱的光亮。但我们从未摆脱在动物生涯里我们被迫仅从一个角度看待万物的事实。

科学尝试逃离地理与年代的牢笼。在物理上，时空坐标的原点完全随机，而物理学家却致力于说明，对他而言毫无意义的事物，对天狼星或河外星云的居民同样适用。

这又是解放的时代。历史和地理让我们摆脱现在，天文学让我们摆脱此处。大脑中充满这些研究的人会觉得一些事偶然，或几乎微不足道，实际上他的自我占有了时空川流的某一部分。他的才智逐渐变得越来越独立于那些生理需求。在这方面，它需要通则、眼界和力量，而这些对于思考被困于动物需求的人来说是不可能的。

所有文明国家多少都能感知到：一个博学之士不被期望只种植他自己的食物，满足于有大量无用的时间可供消耗，为仅不过是活下去的问题忧心。当然，它仅能通过一个社会机制完成，在此机制下客观的态度多少有可能通行。我们全都变得沉迷于就生存而言是必须的动物需求，但有某些能力的人能自由发展出摆脱自身需求的思考和感受的方式，此发展会被发现具有价值。这与了解某方面知识相关，但最相关的是那种有哲学特征的总览。

** 宇宙的不同图景

如果读些过去大哲学家的理论，你会发现大量不同的宇宙图景，它们对人类的想象力有几分好处。一些人认为世界上只有精神，而物理事物其实是幻象。其他人认为只有物质，我们叫做“精神”的只是由某些物质以古怪的方式表现出的而已。现在我还不能说它们中任何一个对世界的看法比另一个更真实，或更有吸引力。我想说的是，体会这些不同的世界图景带来的训练能延伸心智，使其更能领会新的、也许更有用的假说。

这是哲学能带来的另一个才智方面的用处，尽管在这方面它时常失败。人们应受教诲，意识到人易犯错、许多对未受教育者可靠的东西其实充满不确定性。孩子最初会拒绝相信地球是圆的，坚决断言他们看到它是平的。

但我记得对不确定性最重要的应用是在社会制度和理论方面。形成了客观的思考习惯时，我们才会有能力审视对自身阶层、教派的信念，并同样公正地审视其他人。我们应发现，我们最坚定并热情地持有的信念往往严重缺少证据。当一大群人类肉体相信甲时，另一大群人类肉体相信乙，那么每具肉体都会自发地憎恨那些相信其他荒谬事物的人。

此倾向最好的疗法是训练依照证据形成判断，并放弃缺少证据的确定性。不仅是宗教信仰和政治信念，社会风俗也同样适用。人类学研究显示，有极其多样的社会风俗存在，而一些社会坚持着可能被认为与人类天性相违背的习惯。此类知识作为教条主义的解毒剂非常有价值，尤其是在相互对立的教条主义成为人类主要威胁的这个我们自己的时代。

客观思考和客观感觉的形成起码同样重要，并且应同样产生于哲学观点。我们的欲望，如感官，根本上是以自我为中心。此自我中心特征与我们的道德体系相抵触。在一个例子中（其他也一样），渴求之物并不完全是失去动物禀赋——它是生活之必须——而是增加更开明、更普遍和更少被个人情况影响的东西。我们不该钦佩一个不喜欢自己孩子犹如不喜欢其他孩子的父母，而应该钦佩一个从对自己孩子的关爱而生发出更普遍关爱的人。我们不该钦佩一个对食物漠不关心以至营养不良的人，而应该钦佩一个从自己对食物的需要的知识而生发出对饥饿者普遍同情的人。

哲学在感受方面能做的与其在思考方面能做的极其相似。它不应该从个人生活中减去，而应加入。就像对哲学家的智力调查比未受教育者的更广泛，所以他欲望的范围也应该更广泛。据说佛陀宣称只要有人在受苦他就不会快乐。这把事情带向了一个极端，而且从字面上理解也过度了，但这阐明了我在说的感觉的普遍化。一个以哲学方式感觉的人不仅思考，还会以他自己的经验记录什么东西对他好、什么东西对他坏，并希望如同为自己一样为他人保护前者、避免后者。

** 社会进步的根源

道德准则应像科学一样普遍化，以人力之所及，从此地和现在的暴政中解放出来。有一个简单法则可以测试基本的道德准则，即：“基本的道德准则不能包含专有名词。”我的意思是时空的任何一部分都可以指定为专有名词，个人的名字是，地区、国家和历史时期的名称也是。而当我说基本的道德准则应有此特征时，是在表明超越客观智力认同的东西，因为只要它是全部，一个基本准则就可能会对行为产生非常微小的影响。我意指更活跃之物，真实的欲望或冲动的本性之物，同情的想象的根源之物。它来自于大多数社会进步曾提出并且仍必须提出的一个广义种类。如果你的意愿和希望局限于你自己，或你的家庭，或国家，或阶级，或你所信之教义的信徒，你会发现你所有的喜好和善意感都伴随着厌恶与敌意。从人类感觉的此二元性中，几乎产生了人类生命中的所有罪恶——残暴、压迫、迫害和战争。如果我们的世界要摆脱这些威胁它的灾难，人类必须学着更少地在同情方面受限。

这无疑在一定程度上是真实的，但它从没像现在一样比以往更真实。人类由于科学与科学技术，为了罪恶而联合，却从没为了善联合。他们学习全世界彼此毁灭的科技，而不是更吸引人的全世界团结合作的科技。后者的失败有种种原因：情绪性的缺陷，对所属群体狭隘的同情，沉溺于对其他群体的憎恶和恐惧。

以我们现有的科技，全球协作能消除贫困和战争，将所有人类带至迄今不存在的幸福和安康的水平。但尽管这显而易见，人类仍旧偏爱将合作限于他们自己的群体，肆意向其他群体投射凶残的敌意，这使日常生活充满了可怕的灾难景象。以各人利益行事产生了荒唐和悲剧性的缺陷，它不向任何外部事物撒谎，而只向我们自己易动感情的天性。如果我们总是像科学家一样客观地感受，就能明白我们的分裂和冲突是多么愚蠢，不久就能察觉到我们自己的利益能与其他人的协调，但毁灭他人的意愿却不能。狂热的教条主义是我们时代的一大罪恶，根本上是智力方面的缺陷，并且如我之前所说，哲学补给是一个人智力的解毒剂。但许多教条主义有情绪上的原因：即恐惧。人们以为只有紧密的社会团体才能面对敌人，而对正统观念的微小偏离会对战争产生不利影响。狂热的民众是偏执的民众。我不认为他们在此明智。恐惧很少激起理性行为，却频繁煽动越来越恐怖的危险行为。

实际情况是荒谬的教条主义在世界的大片地区扩散。在完全客观感受到危险的地方，哲学的生发是最好的疗法。斯宾诺莎也许是有如我所说的感受方式的绝佳榜样，他在生命的最后一天如健康时一样，保持着对他人友善的关切。对于一个意愿和希望都极大地超越了自身生命的人而言，不会有恐惧的时刻——它只存在于那些欲望受限的人身上。他明白，他死后会有其他人继续他的事业，从未有过的大灾难早晚会被克服。他将人类看做一个整体，将历史看做逐渐摆脱动物屈服于自然的一个过程。如果他没有哲学去避免狂乱的恐慌、发展出对不幸坚韧的忍耐能力，这些就不会像希望的那样容易。我不能妄称这样一个人会始终快乐。一个人在这样一个世界几乎不可能始终快乐：我们凝视可能来临的灾难，发现将遭受令人困惑的绝望与骇人的恐怖，但我坚信一个真正的哲学家能更少像其他人那样如此。

[fn:1] Bertrand Russell, “PORTRAITSFROM MEMORY and Other Essays,” KINGSPORT PRESS, 1956, pp. 178–184.
