#+title: 第二章
#+date: 2022-12-07

穿过马路，古老的榆树形成了一排围墙，布鲁克菲尔德学校就在其后，蔓草覆盖着它，在秋季呈现为一片赤褐。一群十八世纪的建筑坐落在学校方场中央，远处是几英亩运动场，接着是从属的布鲁克菲尔德地方、空旷的沼泽地乡村。布鲁克菲尔德，就像韦瑟比说的，是所老学校。伊丽莎白女王一世在位时，它作为文法学校建立，如果运气好些，也许已经和哈罗公学[fn:1]一样有名了。但它的运气并没那么好，因为学校时盛时衰，有时衰落得几乎不存在，有时几乎称得上辉煌。乔治一世在位期间是它的一个辉煌时期，主要的建筑物被建造，还增添了许多新的。之后，在拿破仑战争和维多利亚时代中期之间，学校在人数和声誉方面都再次衰落。韦瑟比1840年来到，多少使它振作起来；但在随后的历史中，它再没能达到一流学校的高度。不过它总归是个不错的二等学校。一些贵族家庭支持着它，而它也为时代提供了相当多创造历史的人物——法官，国会议员，殖民地行政官，一些贵族和主教。但大多数成为了商人，制造商，职业人员，和许多乡绅与牧师。它是这样一种学校：被提起时，势利眼多少会承认自己听说过。

但若不是这样，它就不会聘用契普斯了。因为契普斯无论以社会地位还是学识而论，都仅是个体面人物，并不比布鲁克菲尔德出类拔萃。

起初，他经过一段时间认识到了这点。并不是因为他自吹自擂或骄傲自满，而是在二十岁的头几年，他和多数这个年纪的年轻人一样，怀揣着雄心抱负。他梦想着最终能获得校长职务，或至少是一所真正一流的学校里的中级领导职务。只是慢慢地，经历了多次尝试和失败后，他意识到了自己能力欠缺。比如他的学历普普通通，而他所管学生的纪律，尽管还行且在提高，但并非始终绝对可靠。他也没有私人财产和任何重要的家族关系。大约1880年，待在布鲁克菲尔德满10年，他开始承认形势大不利于他升迁到别处；但也是在此时，他开始觉得如果能留在这儿也还不错。四十岁时，他扎了根，安定了下来，十分快活。五十岁时，在一个新来的年轻校长手下，他是布鲁克菲尔德老一辈宴会上的主宾、所有涉及学校历史和传统问题的上诉法院。1913年，他退休了，被赠与一张支票、一张书桌和一挂钟，住在了路对面的薇琪特太太那里。体面的生涯，体面地结束。学期终了时喧闹的晚宴上，他们都向老契普斯三次欢呼。 

三次欢呼，的确。但事情还没完，这是意料之外的尾声，是为悲剧观众再演的节目。

[fn:1] 英国哈罗城的一所著名的男生寄宿学校，创于1571年。
