#+title: 第十章
#+date: 2022-12-25

1900年，老梅尔德伦突然因肺炎去世，他接替韦瑟比任了三十年校长。在新校长接任前，契普斯成了布鲁克菲尔德的代理校长。校董们不大可能将这次认命变为永久，所以当他们请来一个年仅三十七岁的青年时，契普斯并不怎么失望。新校长带着光耀夺目的比赛第一名和牛津大学代表的标志，个性独特，只要竖起一条眉毛就能让整个大礼堂寂然无声。契普斯根本不是这种人的对手，过去不是将来也不是，他明白这点。他温和多了，没那么凶狠。

他1913年退休前的这些日子缀满了记得清清楚楚的景象。

五月的一个早晨，校钟在不是平常的时间敲了，每个人都被召集到大礼堂集合。新校长罗尔斯顿非常傲慢，深知自己的地位，凝视着全场的人，神态严肃冰冷，像是预示着什么。“英王爱德华七世陛下今早离世，你们一定都非常悲痛......今天下午不上课，但四点半在教堂举行礼拜仪式。”

一个夏日的早晨，布鲁克菲尔德附近的铁路线上。铁路工人在罢工，士兵驾驶着机车，石头扔向火车。布鲁克菲尔德的学生在这条铁路线上巡逻，他们觉得整件事挺有趣的。契普斯负责这件事，他站在不远处，正和村社大门口的一个男人说着话。小克里克雷德走来。“请问，先生，要是我们碰到罢工工人怎么办？”

“你想碰见个吗？”

“我——我不知道，先生。”

可怜的孩子——他讲到他们时，仿佛他们是从动物园里逃出来的什么怪兽！“嗯，这里就有一个——嗯——你得见见琼斯先生——他是罢工工人。他值勤时管理车站的信号所。你可是常常把命交到他手上。”

之后这件事传遍了学校：契普斯，在跟罢工者交谈。在跟罢工者交谈！从谈话的情况来看，他们还十分友好呢。

契普斯将这件事思量了许多次，总觉得凯瑟琳会赞成，而且还会觉得有趣。

因为无论发生什么，政治如何弯曲变形，他对英国、对英国人都抱有信心，对布鲁克菲尔德也是，他觉得布鲁克菲尔德的最终价值取决于它是否有尊严地、协调地适应英国国情，成为它的一部分。一个印象留在了他的脑海里，随着一年年时光的流逝越来越清晰——英国安逸的日子差不多已经过去了，驶入了稍有错误就将酿成大祸的航道。他记得维多利亚女王在位六十周年的纪念日，布鲁克菲尔德放了一天假，他带着凯瑟琳去伦敦看庆祝行列。那个传奇式的老妇人坐在她的马车上，像是摇摇欲坠的木偶，她象征了许多东西，令人印象深刻，如今正像她自己一样，将近末日。将近末日的是这个世纪，还是一个时代？

接着是爱德华时代狂乱的十年，像是电灯熄灭前发出了更亮更白的光。

罢工和闭厂，香槟晚宴和失业工人的游行示威，华工，关税改革，英国战舰“无畏号”，马可尼，爱尔兰自治，克里平医生，争取妇女参政的女性，查特吉的诗行......

一个四月的晚上，多风且阴雨。学生对维吉尔作品的第四种形式不大理解，因为报纸上有新闻在激动人心。年轻的格雷森尤其心不在焉，看起来心事重重。他是个文静而胆怯的孩子。

“格雷森，在其他同学放学后——嗯——留下来。”

然后：

“格雷森，我不想——嗯——太严肃，因为你平时功课——嗯——总是很好，但今天——你似乎——嗯——根本没用心。是出什么事了吗？”

“没——没有，先生。”

“好吧——嗯——这事就过去吧——不过——嗯——我希望你下回能用点心。”

第二天早上，格雷森的父亲在泰坦尼克号船上的消息哄传全校，至今还没有关于他生死安危的消息穿来。

格雷森被免予上课。学校一整天都激动地关注着他所焦虑的事情。最后消息传来，他父亲在获救者之列。

契普斯与这个男孩握着手。“好啊，嗯——我很高兴，格雷森。结局欢乐。你一定对生活感到非常满意。”

“是的，先生。”

一个文静且胆怯的孩子。契普斯后来注定要慰问的倒是老格雷森，而不是小格雷森。
