#+title: 第十一章
#+date: 2023-02-28

然后是和罗尔斯顿吵嘴。趣事，契普斯从没喜欢过他。虽说他能力强、硬心肠、有雄心壮志，可不知怎的，不大讨人喜欢。诚然，他提高了布鲁克菲尔德作为一所学校的地位，首次令人印象深刻地有了较长的申请入学者名单。罗尔斯顿精力充沛，很有魄力，可你必须提防他。

契普斯从未操心于防他，他也不被这人吸引，但他乐意且足够忠诚地为他工作。更确切地说，是为布鲁克菲尔德工作。他也知道罗尔斯顿不喜欢他，不过这无关紧要。他觉得自己年长资深，足以避免那些不为罗尔斯顿喜欢的教师的命运。

然而在1908年，他刚满六十岁，罗尔斯顿温和的最后通牒突然来了。“契宾先生，你想过要退休吗？”

在布满书籍的书房里，契普斯看着他四周，被这问题吓了一跳，想知道罗尔斯顿为什么这么问。最后，他说：“不——嗯——我不能说——嗯——我仔细考虑过这问题。”

“好吧。契宾先生，希望你考虑这建议。董事会同意给你充足的养老金。”

契普斯突然发起火来。“但——嗯——我不想——退休。我也不需要——嗯——考虑它。”

“不过我建议你这么做。”

“可是——嗯——我不明白——为什么——我该退休！”

“那么，事情就有点难办了。”

“难办？为什么——难办？”

接着他们就吵起来了，罗尔斯顿越来越冷酷、强硬，而契普斯越来越激动、生气，直到最后罗尔斯顿冷冰冰地说：“既然你要让我直言不讳，那么，契宾先生，你就听着吧。 过去一段时间，你没在这发挥自己的作用。你教学方式老式、懒散；你个人习惯邋遢；你还不听我的指示，这要是在个年轻人身上，我就认为是不服从上级了。这不对，契宾先生，你该把我长期容忍归因于我的克制。”

“但是……”契普斯全然愣住了，开始说；接着他抓住了那不寻常的指责中的几个孤立的词。“你说——嗯——邋遢？”

“对，看看你穿的长袍。我恰巧知道你的长袍是整个学校的笑料。”

这契普斯也知道，但并不认为这是个可悲的事。

他继续说：“你还说——嗯——关于不服从的事？”

“不，我没这么说。我说的是在年轻人身上我会这么认为。至于你，那也许是散漫与固执的混合。比如拉丁读音的问题——我记得许多年前就告诉过你，我要让整个学校采用新式发音法。其他教师都照我说的做了，可你却偏坚持你的老方法，这结果只能是混乱和低效。”

契普斯终于有具体的目标可以对付了。“噢，原来是这个？”他轻蔑地回答。“这个，我——嗯——我承认我不同意新式发音。过去也从没有过。嗯——在我看来，新式发音简直是胡闹。让学生在学校说‘Kickero’，而他们离开学校说的是‘Cicero[fn:1]’——要是他们——嗯——还说的话。还有——啊，天哪——你不教他们读‘vicissim’，而是‘We kiss ’im’！哼——哼！’他轻笑了一下，忘了他是在罗斯特的书房，而不是自己气氛友好的教室。

“诺，你就是这样，契宾先生——这只是我抱怨的一个例子。你持有一种观点，我持有另一种，而且你不肯让步，那也就没有其他合适的选择了。我要把布鲁克菲尔德办成一所全新的学校。我自己是研究科学的人，不过不反对古希腊语和拉丁语——只要教的高效。它们是死语言不能成为用死教学方法教它们的理由。我猜，契宾先生，你的拉丁和希腊语课还和我十年前来这时完全一样吧？”

契普斯缓慢而自豪地回道：“至于那个——嗯——它们和你前任——梅尔德伦先生——来这时一样，那是三十年前。我们在这开始，梅尔德伦先生和我，是——嗯——1870年。而且是——嗯——梅尔德伦先生的前任，韦瑟比先生第一个赞成我的教学大纲的。‘你来教四年级的西塞罗课吧，’他对我说。也是Cicero——不是Kickero。”

“非常有趣，契宾先生，不过这又一次证明了我的看法——你过分活在了过去，在当下和未来却活得不够。时代在变，无论你是否意识到。现代的父母付了三年学费，要求学到一些比一鳞半爪没人说的语言更多的东西。而且你教的学生该学的都没学好。去年的初级考试他们没一个及格的。”

接着有一连串想法汹涌而来，来不及用语言表达，契普斯只能在心里回答。这些考试、证书等等——它们有什么要紧的？并且所有这些效率和时新——那又有什么要紧的？罗尔斯顿想把布鲁克菲尔德办得像工厂一样——以金钱和机器为基础生产势利文化的工厂。以家族和广大田地为基础的古老的绅士传统在改变，因为它们当然应该如此。但罗斯特不是在把它们扩大为一种公爵和清洁工都包括在内的真正的民主，而只是在把它们缩小为一个有巨额存款的银行账户。富家子弟来布鲁克菲尔德的不多。授奖典礼日的游园会如同阿斯科特赛马会。罗尔斯顿认识那些伦敦俱乐部的富家伙，就劝使他们相信布鲁克菲尔德是所有前途的学校，而且他们因为不能靠花钱疏通进入伊顿公学或哈罗公学，就争相上钩。他们中的一些是坏家伙——尽管一些足够体面。金融家、公司创办人、药丸制造商。他们中的一些人每周给孩子五英镑零花钱。庸俗……浮华……这个时代忙乱和烂透了的一切……有一次，契普斯惹上了麻烦，因为他对一个叫艾萨克斯坦的学生的名字和世系开玩笑。学生把这件事写信告诉了家里，结果老艾萨克斯坦给罗尔斯顿写了封怒气冲冲的信。动不动就生气，没幽默感，没分寸感——这就是他们的毛病，这些新一代的家伙……没分寸感。分寸感可比一切都重要，布鲁克菲尔德应该教教他们——而不是这么多的拉丁语、希腊语、化学、力学。并且你不能期望用出考题和发证书就能测验分寸感……

所有这些都在反对和气愤的一瞬间闪过他的脑海，不过他没说一个关于这的字。他只是拉好他破烂的长袍，“哼——哼”着走开几步。他已经争论得够多了。
他在门口转身，说：“我没——哼——想辞职——你——哼——看着办吧！”

二十五年后冷静地回顾当时的争吵，契普斯竟然会打心眼里为罗尔斯顿感到抱歉。尤其是罗尔斯顿全然不知道他在对付的是什么势力时。而且，在这点上，契普斯自己也是这样。两人都没能正确估计到布鲁克菲尔德传统多么顽强，以及这种传统怎么时刻准备着保卫自己和自己的保卫者。事情是这样碰巧发生的，那天早上有个小学生正等着见罗尔斯顿，整个会谈期间都在门外听着，这让他兴奋不已，不由自主地告诉了他的朋友。在极短的时间内，他们中的一些又告诉了父母，于是很快，罗尔斯顿攻击契普斯并要求他辞职的事人尽皆知。其惊人的结果是，同情与偏袒自然迸发，这些契普斯在最荒诞的梦中也不会想到。他惊讶地发现罗尔斯顿成了完全不受欢迎的人。他令人畏惧、受人尊敬，可不被喜欢，结果在契普斯这个问题上，讨厌上升到战胜畏惧、甚至破除尊敬的程度。当时有传闻出现，说如果罗尔斯顿成功赶走了契普斯就会有人公开闹事。教师护卫他，尽管他们中的一些年轻人觉得契普斯老派得无可救药，因为他们讨厌罗尔斯顿像监督奴隶一样监督他们，并且将契普斯看做比较可靠的支持者。于是有一天，董事会主席约翰·里弗斯爵士，访问布鲁克菲尔德，没理会罗尔斯顿，直接去看了契普斯。“好家伙，里弗斯，”契普斯常说，把这件事给薇琪特太太讲了许多遍。“在班上不是个——嗯——聪明的学生——我记得他没——嗯——学会动词。不过如今——嗯——我在报纸上看到——他们封他为——嗯——男爵。你看就是这样——嗯——就是这样。”

1908年的一个早上，他们在当时没人的板球场上闲逛，约翰爵士挽着契普斯的手臂，说：“契普斯，老朋友，我听说你和罗尔斯顿大吵了一场。听到这事我很难过，为了你——但我想让你知道董事会都站在你这边。我们不大喜欢那家伙。聪明啊什么的，可太聪明了，要是你问我的话。自称在交易所耍了些花招，把捐赠给学校的基金翻了倍。我想，不过需要留点心眼。要是他向你耀武扬威，就客气地对他说见鬼去吧。董事都不想你辞职。要是没有你，布鲁克菲尔德就不一样了，他们知道。我们都知道。如果你高兴的话，就在这儿待到一百岁——我们当然也希望你能。”

听到这番话时——以及后来每每提及——契普斯不禁痛哭起来。

[fn:1] 西塞罗，罗马政治家、演说家、作家，生于公元前106年，卒于公元前43年。
